[FEATURE]
Learnosity/learnosity-demos pull request #167
Opened 2021-11-26 03:59 UTC by christian-crisologo-lrn

Initial setup for GCA frontend codebase. 
This is just a frontend-only for the style guide placeholder

- [ ] NPM + Yarn
- [ ] Webpack with dev + prod build
- [ ] SCSS support
- [ ] ReactJs + typescript
- [ ] Eslint + Prettifier

TODO: 

- [ ] Github workflow to run the build when the branch merged or when the PR closed

2021-11-30 04:49 UTC, jack-vo requested changes

2021-11-30 04:49 UTC, jack-vo commented on www/assessment/customization/style-guide/.npmrc
> +//npm.pkg.github.com/:_authToken=${NPM_TOKEN}
We do not use anything from LRN private packages here so remove this file

2021-11-30 04:49 UTC, jack-vo commented on www/assessment/customization/style-guide/.eslintrc
> +    "__LRN_DEVELOPMENT": true,
This is not necessary as you are not building a proper client facing API that needs to differentiate bw DEV vs PROD

2021-11-30 04:49 UTC, jack-vo commented on www/assessment/customization/style-guide/jest.config.js
> +const path = require('path');
Remove this file, I am not sure we will even have unit-tests in this first phase

2021-11-30 04:49 UTC, jack-vo commented on www/assessment/customization/style-guide/tests/specs/@testConfig/jest.setup.js
> +// Any setup that we need to do before executing all the tests
Same here

2021-11-30 04:49 UTC, jack-vo commented on www/assessment/customization/style-guide/tests/specs/@testConfig/styleMock.js
> +module.exports = {};
And here

2021-11-30 04:49 UTC, jack-vo commented on www/assessment/customization/style-guide/tsconfig.json
> +            "@testConfig/*": ["tests/specs/@testConfig/*"]
Delete this

2021-11-30 04:49 UTC, jack-vo commented on www/assessment/customization/style-guide/webpack.config.base.js
> +const MiniCssExtractPlugin = require('mini-css-extract-plugin');
Remove all this, if you are going to use predefined Libraries for UI like Material UI, keep this set up as small as possible

2021-11-30 04:49 UTC, jack-vo commented on www/assessment/customization/style-guide/webpack.config.base.js
> +        new MiniCssExtractPlugin({
Strip this out

2021-11-30 04:49 UTC, jack-vo commented on www/assessment/customization/style-guide/webpack.config.base.js
> +/* globals require, __dirname */
Rename this file to `webpack.config.js` only

2021-11-30 04:49 UTC, jack-vo commented on www/assessment/customization/style-guide/webpack.config.prod.js
> +/*global require */
Remove this file

2021-11-30 04:49 UTC, jack-vo commented on www/assessment/customization/style-guide/webpack.config.dev.js
> +const webpack = require('webpack');
Remove this file

2021-11-30 04:49 UTC, jack-vo commented on www/assessment/customization/style-guide/README.md
> +##Style guide custimization for Assessment UI
Update this README

2021-11-30 04:49 UTC, jack-vo commented on www/assessment/customization/style-guide/webpack.config.base.js
> +                    MiniCssExtractPlugin.loader,
Remove this line

2021-12-05 22:59 UTC, eric-guo-lrn approved these changes
LGTM

2021-12-06 23:22 UTC, merged